<?php

use Illuminate\Database\Seeder;

class SanPhamTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $today = new DateTime('2020-02-27 09:00:00');
        $list=[
            [
                'sp_ma' => 1,
                'sp_ten' => 'ÁO THUN U1ATN020001',
                'sp_gia' => '235000',
                'sp_hinh' => "aothunU1ATN020001.jpg",
                'sp_thongTin' => 'Áo thun U1ATN020001 màu đen với logo đơn giản tay ngắn, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 2,
                'sp_ten' => 'ÁO THUN M2ATN010028',
                'sp_gia' => '245000',
                'sp_hinh' => "aothunM2ATN010028.jpg",
                'sp_thongTin' => 'ÁO thun M2ATN010028 màu vàng với họa tiết Puma tay ngắn, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 3,
                'sp_ten' => 'ÁO THUN M2ATN129011',
                'sp_gia' => '245000',
                'sp_hinh' => "aothunM2ATN129011.jpg",
                'sp_thongTin' => 'Áo thun M2ATN129011 tay ngắn, màu đen, đa họa tiết, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 4,
                'sp_ten' => 'ÁO THUN U1ATD129004',
                'sp_gia' => '265000',
                'sp_hinh' => "aothunU1ATD129004.jpg",
                'sp_thongTin' => 'Áo thun U1ATD129004 ráp tay, màu xám đen, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 5,
                'sp_ten' => 'ÁO THUN ATB109001',
                'sp_gia' => '195000',
                'sp_hinh' => "aothunATB109001.jpg",
                'sp_thongTin' => 'Áo thun ATB109001 tay ngắn, màu đen, logo lớn, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 6,
                'sp_ten' => 'ÁO SƠ MI M1SMD020001',
                'sp_gia' => '275000',
                'sp_hinh' => "aosomiM1SMD020001.jpg",
                'sp_thongTin' => 'Áo sơ mi M1SMD020001 trắng tay dài',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 7,
                'sp_ten' => 'ÁO SƠ MI M1SMD020002',
                'sp_gia' => '275000',
                'sp_hinh' => "aosomiM1SMD020002.jpg",
                'sp_thongTin' => 'Áo sơ mi M1SMD020002 sọc xám đen tay dài',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 8,
                'sp_ten' => 'ÁO SƠ MI M1SMD010001',
                'sp_gia' => '295000',
                'sp_hinh' => "aosomiM1SMD010001.jpg",
                'sp_thongTin' => 'Áo sơ mi M1SMD010001 đen tay dài',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 9,
                'sp_ten' => 'ÁO SƠ MI M1SMD010002',
                'sp_gia' => '295000',
                'sp_hinh' => "aosomiM1SMD010002.jpg",
                'sp_thongTin' => 'Áo sơ mi M1SMD010002 đỏ tay dài phối họa tiết trắng',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 10,
                'sp_ten' => 'ÁO SƠ MI SMB099002GN',
                'sp_gia' => '285000',
                'sp_hinh' => "aosomiSMB099002GN.jpg",
                'sp_thongTin' => 'Áo sơ mi SMB099002GN màu trắng khói pha xanh tay dài',
                'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 11,
                'sp_ten' => 'QUẦN JEAN M2QJN129004',
                'sp_gia' => '425000',
                'sp_hinh' => "quanjeanM2QJN129004.jpg",
                'sp_thongTin' => 'QUẦN JEAN M2QJN129004 với gam màu sáng, thêu chữ nhỏ',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 12,
                'sp_ten' => 'QUẦN JEAN M1QJN129003',
                'sp_gia' => '365000',
                'sp_hinh' => "quanjeanM1QJN129003.jpg",
                'sp_thongTin' => 'QUẦN JEAN M1QJN129003 đen',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 13,
                'sp_ten' => 'QUẦN JEAN M1QJN119009',
                'sp_gia' => '445000',
                'sp_hinh' => "quanjeanM1QJN119009.jpg",
                'sp_thongTin' => 'QUẦN JEAN M1QJN119009 xanh đen rách cá tính',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 14,
                'sp_ten' => 'QUẦN JEAN QJB109006',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanQJB109006.jpg",
                'sp_thongTin' => 'QUẦN JEAN QJB109006 đen năng động',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 15,
                'sp_ten' => 'QUẦN JEAN M2QJN129002',
                'sp_gia' => '425000',
                'sp_hinh' => "quanjeanM2QJN129002.jpg",
                'sp_thongTin' => 'QUẦN JEAN M2QJN129002 rách với gam màu sáng năng động',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 16,
                'sp_ten' => 'QUẦN TÂY NAM KKB089016',
                'sp_gia' => '315000',
                'sp_hinh' => "quantayKKB089016.jpg",
                'sp_thongTin' => 'QUẦN TÂY NAM KKB089016 màu đen thanh lịch',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 17,
                'sp_ten' => 'QUẦN TÂY NAM KKB089010',
                'sp_gia' => '315000',
                'sp_hinh' => "quantayKKB089010.jpg",
                'sp_thongTin' => 'QUẦN TÂY NAM KKB089016 màu trắng sang trọng',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 18,
                'sp_ten' => 'KAKI NAM KKB079002BL',
                'sp_gia' => '345000',
                'sp_hinh' => "kakiKKB079002BL.jpg",
                'sp_thongTin' => 'QUẦN KAKI NAM KKB079002BL đen',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 19,
                'sp_ten' => 'QUẦN TÂY KKB059005',
                'sp_gia' => '365000',
                'sp_hinh' => "quantayKKB059005.jpg",
                'sp_thongTin' => 'QUẦN TÂY NAM KKB059005 sọc đen',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 20,
                'sp_ten' => 'KAKI NAM 108002NV',
                'sp_gia' => '245000',
                'sp_hinh' => "kaki108002NV.jpg",
                'sp_thongTin' => 'QUẦN KAKI NAM KKB059005 xanh',
                'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 21,
                'sp_ten' => 'ÁO THUN W2ATN010029',
                'sp_gia' => '185000',
                'sp_hinh' => "aothunW2ATN010029.jpg",
                'sp_thongTin' => 'Áo thun W2ATN010029 croptop xanh dương cá tính',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 22,
                'sp_ten' => 'ÁO THUN W2ATD010008',
                'sp_gia' => '185000',
                'sp_hinh' => "aothunW2ATD010008.jpg",
                'sp_thongTin' => 'Áo thun W2ATD010008 ôm body tay dài , sọc ngang',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 23,
                'sp_ten' => 'ÁO THUN W2ATD010007',
                'sp_gia' => '225000',
                'sp_hinh' => "aothunW2ATD010007.jpg",
                'sp_thongTin' => 'Áo thun W2ATD010007 in hoạt hình vui nhộn, phối tay xanh',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 24,
                'sp_ten' => 'ÁO LEN W2ALD010003',
                'sp_gia' => '315000',
                'sp_hinh' => "aolenW2ALD010003.jpg",
                'sp_thongTin' => 'Áo len W2ALD010003 sọc trắng xinh xắn',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 25,
                'sp_ten' => 'ÁO LEN W2ALD129002',
                'sp_gia' => '295000',
                'sp_hinh' => "aolenW2ALD129002.jpg",
                'sp_thongTin' => 'Áo len W2ALD129002 xanh lam tay dài đáng yêu',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 26,
                'sp_ten' => 'ÁO SƠ MI W2SMD010019',
                'sp_gia' => '235000',
                'sp_hinh' => "aosomiW2SMD010019.jpg",
                'sp_thongTin' => 'Áo sơ mi W2SMD010019 xám in chữ đen',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 27,
                'sp_ten' => 'ÁO SƠ MI W2SMD010018',
                'sp_gia' => '235000',
                'sp_hinh' => "aosomiW2SMD010018.jpg",
                'sp_thongTin' => 'Áo sơ mi W2SMD010018 trắng đen phối hoạt hình cực cool',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 28,
                'sp_ten' => 'ÁO SƠ MI W2SMD129015',
                'sp_gia' => '235000',
                'sp_hinh' => "aosomiW2SMD129015.jpg",
                'sp_thongTin' => 'Áo sơ mi W2SMD129015 phối caro nâu vàng',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 29,
                'sp_ten' => 'ÁO SƠ MI W2SMD129009',
                'sp_gia' => '235000',
                'sp_hinh' => "aosomiW2SMD129009.jpg",
                'sp_thongTin' => 'Áo sơ mi W2SMD129009 phối caro đen đỏ',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 30,
                'sp_ten' => 'ÁO SƠ MI W2SMD129002',
                'sp_gia' => '255000',
                'sp_hinh' => "aosomiW2SMD129002.jpg",
                'sp_thongTin' => 'Áo sơ mi W2SMD129002 trắng không nhăn',
                'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 31,
                'sp_ten' => 'QUẦN JEAN W2QJN010018',
                'sp_gia' => '440000',
                'sp_hinh' => "quanjeanW2QJN010018.jpg",
                'sp_thongTin' => 'Quần jean W2QJN010018 rách với gam màu sáng đáng yêu',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 32,
                'sp_ten' => 'QUẦN JEAN W2QJN129005',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanW2QJN129005.jpg",
                'sp_thongTin' => 'Quần jean W2QJN129005 ống rộng với gam màu sáng cá tính',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 33,
                'sp_ten' => 'QUẦN JEAN W2QJN129004',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanW2QJN129004.jpg",
                'sp_thongTin' => 'Quần jean W2QJN129004 xanh ống rộng',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 34,
                'sp_ten' => 'QUẦN JEAN QJG109005',
                'sp_gia' => '340000',
                'sp_hinh' => "quanjeanQJG109005.jpg",
                'sp_thongTin' => 'Quần jean QJG109005 trắng xanh cá tính',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 35,
                'sp_ten' => 'QUẦN JEAN QJG039023',
                'sp_gia' => '440000',
                'sp_hinh' => "quanjeanQJG039023.jpg",
                'sp_thongTin' => 'Quần jean QJG039023 đen',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 36,
                'sp_ten' => 'QUẦN SHORT QSG109003',
                'sp_gia' => '245000',
                'sp_hinh' => "quansortQSG109003.jpg",
                'sp_thongTin' => 'Quần short QSG109003 màu bạc',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 37,
                'sp_ten' => 'QUẦN SHORT W2SKK129002',
                'sp_gia' => '215000',
                'sp_hinh' => "quansortW2SKK129002.jpg",
                'sp_thongTin' => 'Quần short W2SKK129002 kaki màu nâu sáng',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 38,
                'sp_ten' => 'QUẦN SHORT QSG069007',
                'sp_gia' => '275000',
                'sp_hinh' => "quansortQSG069007.jpg",
                'sp_thongTin' => 'Quần short QSG069007 với gam màu sáng năng động',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 39,
                'sp_ten' => 'QUẦN SHORT QSG049015',
                'sp_gia' => '275000',
                'sp_hinh' => "quansortQSG049015.jpg",
                'sp_thongTin' => 'Quần short QSG049015 trắng',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 40,
                'sp_ten' => 'QUẦN SHORT 088005BL',
                'sp_gia' => '235000',
                'sp_hinh' => "quansort088005BL.jpg",
                'sp_thongTin' => 'Quần short 088005BL đen',
                'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 41,
                'sp_ten' => 'ĐỒ ĐÔI D1ATD020002',
                'sp_gia' => '570000',
                'sp_hinh' => "aothunD1ATD020002.jpg",
                'sp_thongTin' => 'Đồ đôi D1ATD020002 áo thun tay dài, màu vàng',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 42,
                'sp_ten' => 'ĐỒ ĐÔI D2ATD119011',
                'sp_gia' => '510000',
                'sp_hinh' => "aothunD2ATD119011.jpg",
                'sp_thongTin' => 'Đồ đôi D1ATD020002 áo thun tay dài, màu đen',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 43,
                'sp_ten' => 'ĐỒ ĐÔI D2ATP129011',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunD2ATP129011.jpg",
                'sp_thongTin' => 'Đồ đôi D2ATP129011 áo thun tay ngắn, màu trắng có cổ',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 44,
                'sp_ten' => 'ĐỒ ĐÔI D2ATP129010',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunD2ATP129010.jpg",
                'sp_thongTin' => 'Đồ đôi D2ATP129010 áo thun tay ngắn, màu đen có cổ',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 45,
                'sp_ten' => 'ĐỒ ĐÔI D1ATD129001',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunD1ATD129001.jpg",
                'sp_thongTin' => 'Đồ đôi D1ATD129001 áo thun tay dài, màu vàng cute',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 46,
                'sp_ten' => 'ĐỒ ĐÔI D1AKK010002',
                'sp_gia' => '730000',
                'sp_hinh' => "aokhoacD1AKK010002.jpg",
                'sp_thongTin' => 'Đồ đôi D1AKK010002 áo khoác đỏ đen cá tính',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 47,
                'sp_ten' => 'ĐỒ ĐÔI D1AKK119003',
                'sp_gia' => '730000',
                'sp_hinh' => "aokhoacD1AKK119003.jpg",
                'sp_thongTin' => 'Đồ đôi D1AKK119003 áo khoác đen trắng cá tính',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 48,
                'sp_ten' => 'ĐỒ ĐÔI AKF049003BL',
                'sp_gia' => '560000',
                'sp_hinh' => "aokhoacAKF049003BL.jpg",
                'sp_thongTin' => 'Đồ đôi AKF049003BL áo khoác dù đen trắng',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 49,
                'sp_ten' => 'ĐỒ ĐÔI AKF049002GR',
                'sp_gia' => '690000',
                'sp_hinh' => "aokhoacAKF049002GR.jpg",
                'sp_thongTin' => 'Đồ đôi AKF049002GR áo khoác kaki xám trắng',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 50,
                'sp_ten' => 'ĐỒ ĐÔI AKF049002GN',
                'sp_gia' => '690000',
                'sp_hinh' => "aokhoacAKF049002GN.jpg",
                'sp_thongTin' => 'Đồ đôi AKF049002GN áo khoác kaki trắng xanh',
                'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
           
        ];

        DB::table('sanpham')->insert($list);
    }
}
