<?php

use Illuminate\Database\Seeder;

class SanPhamTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $today = new DateTime('2020-02-27 09:00:00');
        $list=[
            [
                'sp_ma' => 1,
                'sp_ten' => 'ÁO THUN B1',
                'sp_gia' => '235000',
                'sp_hinh' => "aothunB1.jpg",
                'sp_thongTin' => 'Áo thun B1 trắng chất liệu cotton mềm mịn, mang lại cảm giác dễ chịu cho người mặc kèm với họa tiết đặc sắc giúp các chàng trai trở nên năng động hơn. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 2,
                'sp_ten' => 'ÁO THUN B2',
                'sp_gia' => '245000',
                'sp_hinh' => "aothunB2.jpg",
                'sp_thongTin' => 'Áo thun B2 đen chất liệu cotton mềm mịn, mang lại cảm giác dễ chịu cho người mặc kèm với họa tiết đặc sắc giúp các chàng trai trở nên năng động hơn. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 3,
                'sp_ten' => 'ÁO THUN B3',
                'sp_gia' => '245000',
                'sp_hinh' => "aothunB3.jpg",
                'sp_thongTin' => 'Áo thun B3 trắng chất liệu cotton mềm mịn, mang lại cảm giác dễ chịu cho người mặc kèm với họa tiết là những chiếc chú gấu Teddy lớn giúp các chàng trai trở nên trẻ trung hơn. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 4,
                'sp_ten' => 'ÁO THUN B4',
                'sp_gia' => '265000',
                'sp_hinh' => "aothunB4.jpg",
                'sp_thongTin' => 'Áo thun B4 vàng chanh chất liệu cotton mềm mịn, mang lại cảm giác dễ chịu cho người mặc kèm với họa tiết đặc sắc giúp các chàng trai trở nên năng động hơn. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 5,
                'sp_ten' => 'ÁO THUN B5',
                'sp_gia' => '195000',
                'sp_hinh' => "aothunB5.jpg",
                'sp_thongTin' => 'Áo thun trơn B5 màu trắng, chất liệu cotton mềm mịn, mang lại cảm giác dễ chịu cho người mặc . Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 6,
                'sp_ten' => 'ÁO SƠ MI B1',
                'sp_gia' => '275000',
                'sp_hinh' => "aosomiB1.jpg",
                'sp_thongTin' => 'Áo sơ mi B1 tay dài màu đen họa tiết trắng, mang lại vẻ đẹp cool ngầu cho các chàng trai. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 7,
                'sp_ten' => 'ÁO SƠ MI B2',
                'sp_gia' => '275000',
                'sp_hinh' => "aosomiB2.jpg",
                'sp_thongTin' => 'Áo sơ mi B2 tay dài màu đen trơn, mang lại vẻ đẹp cool ngầu cho các chàng trai. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 8,
                'sp_ten' => 'ÁO SƠ MI B3',
                'sp_gia' => '295000',
                'sp_hinh' => "aosomiB3.jpg",
                'sp_thongTin' => 'Áo sơ mi B3 tay ngắn màu đen trơn, mang lại vẻ đẹp cool ngầu cho các chàng trai. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 9,
                'sp_ten' => 'ÁO SƠ MI B4',
                'sp_gia' => '295000',
                'sp_hinh' => "aosomiB4.jpg",
                'sp_thongTin' => 'Áo sơ mi B4 tay dài màu trắng trơn, mang lại vẻ đẹp thanh lịch cho các chàng trai. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 10,
                'sp_ten' => 'ÁO SƠ MI B5',
                'sp_gia' => '285000',
                'sp_hinh' => "aosomiB5.jpg",
                'sp_thongTin' => 'Áo sơ mi B5 tay dài màu trắng họa tiết là dòng chữ ORDINARY, mang lại vẻ đẹp cool ngầu cho các chàng trai. Thích hợp cho những bạn từ 60 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 11,
                'sp_ten' => 'QUẦN JEAN B1',
                'sp_gia' => '425000',
                'sp_hinh' => "quanjeanB1.jpg",
                'sp_thongTin' => 'Quần jean trơn B1 với gam màu tối, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 12,
                'sp_ten' => 'QUẦN JEAN B2',
                'sp_gia' => '365000',
                'sp_hinh' => "quanjeanB2.jpg",
                'sp_thongTin' => 'Quần jean rách B2 với gam màu sáng, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 13,
                'sp_ten' => 'QUẦN JEAN B3',
                'sp_gia' => '445000',
                'sp_hinh' => "quanjeanB3.jpg",
                'sp_thongTin' => 'Quần jean trơn B3 với gam màu tối, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 14,
                'sp_ten' => 'QUẦN JEAN B4',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanB4.jpg",
                'sp_thongTin' => 'Quần jean rách B4 với gam màu sáng, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 15,
                'sp_ten' => 'QUẦN JEAN B5',
                'sp_gia' => '425000',
                'sp_hinh' => "quanjeanB5.jpg",
                'sp_thongTin' => 'Quần jean trơn B5 với gam màu trung bình, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 16,
                'sp_ten' => 'QUẦN TÂY B1',
                'sp_gia' => '315000',
                'sp_hinh' => "quantayB1.jpg",
                'sp_thongTin' => 'Quần tây B1 với gam màu sáng, mang lại cảm giác thanh lịch cho các chàng trai, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 17,
                'sp_ten' => 'QUẦN TÂY B2',
                'sp_gia' => '315000',
                'sp_hinh' => "quantayB2.jpg",
                'sp_thongTin' => 'Quần tây B2 với gam màu tối, kẻ sọc trắng, mang lại cảm giác thanh lịch cho các chàng trai, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 18,
                'sp_ten' => 'QUẦN TÂY B3',
                'sp_gia' => '345000',
                'sp_hinh' => "quantayB3.jpg",
                'sp_thongTin' => 'Quần tây trơn B3 với gam màu tối, mang lại cảm giác thanh lịch cho các chàng trai, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 19,
                'sp_ten' => 'QUẦN TÂY B4',
                'sp_gia' => '365000',
                'sp_hinh' => "quantayB4.jpg",
                'sp_thongTin' => 'Quần tây B4 với gam màu sáng, mang lại cảm giác thanh lịch cho các chàng trai, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 20,
                'sp_ten' => 'QUẦN TÂY B5',
                'sp_gia' => '245000',
                'sp_hinh' => "quantayB5.jpg",
                'sp_thongTin' => 'Quần tây B5 với gam màu sáng, mang lại cảm giác thanh lịch cho các chàng trai, thích hợp cho những bạn từ 65 đến 75 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 21,
                'sp_ten' => 'ÁO THUN G1',
                'sp_gia' => '185000',
                'sp_hinh' => "aothunG1.jpg",
                'sp_thongTin' => 'Áo thun G1 croptop đỏ rực, mang lại cảm giác năng động cho các cô nàng cá tính. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 22,
                'sp_ten' => 'ÁO THUN G2',
                'sp_gia' => '185000',
                'sp_hinh' => "aothunG2.jpg",
                'sp_thongTin' => 'Áo thun G2 croptop xanh dương, mang lại cảm giác năng động cho các cô nàng cá tính. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 23,
                'sp_ten' => 'ÁO THUN G3',
                'sp_gia' => '225000',
                'sp_hinh' => "aothunG3.jpg",
                'sp_thongTin' => 'Áo thun G3 croptop màu da người, mang lại cảm giác dễ chịu cho các cô nàng trẻ trung. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 24,
                'sp_ten' => 'ÁO THUN G4',
                'sp_gia' => '315000',
                'sp_hinh' => "aothunG4.jpg",
                'sp_thongTin' => 'Áo thun G4 ôm body, tay dài, sọc 3 màu, mang lại cảm giác năng động cho các cô nàng cá tính. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 25,
                'sp_ten' => 'ÁO THUN G5',
                'sp_gia' => '295000',
                'sp_hinh' => "aothunG5.jpg",
                'sp_thongTin' => 'Áo thun G5 ôm body, tay dài, sọc 2 màu xanh trắng, mang lại cảm giác năng động cho các cô nàng cá tính. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 26,
                'sp_ten' => 'ÁO LEN G1',
                'sp_gia' => '235000',
                'sp_hinh' => "aolenG1.jpg",
                'sp_thongTin' => 'Áo len G1 sọc 3 màu kẹo ngọt, mang lại cảm giác ngọt ngào cho những cô nàng đáng yêu. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 27,
                'sp_ten' => 'ÁO LEN G2',
                'sp_gia' => '235000',
                'sp_hinh' => "aolenG2.jpg",
                'sp_thongTin' => 'Áo len G2 màu ong vàng, mang lại cảm giác ngọt ngào cho những cô nàng đáng yêu. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 28,
                'sp_ten' => 'ÁO LEN G3',
                'sp_gia' => '235000',
                'sp_hinh' => "aolenG3.jpg",
                'sp_thongTin' => 'Áo len G3 màu xanh biển đáng yêu, mang lại cảm giác ngọt ngào cho những cô nàng dễ thương. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 29,
                'sp_ten' => 'ÁO LEN G4',
                'sp_gia' => '255000',
                'sp_hinh' => "aolenG4.jpg",
                'sp_thongTin' => 'Áo len G4 màu xanh biển croptop dễ thương, mang lại cảm giác ngọt ngào cho những cô nàng đáng yêu. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 30,
                'sp_ten' => 'ÁO LEN G5',
                'sp_gia' => '255000',
                'sp_hinh' => "aolenG5.jpg",
                'sp_thongTin' => 'Áo len G5 màu đỏ cùng họa tiết mùa Noel, mang lại cảm giác ngọt ngào cho những cô nàng đáng yêu. Thích hợp cho những bạn từ 40 đến 55 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 31,
                'sp_ten' => 'QUẦN JEAN G1',
                'sp_gia' => '440000',
                'sp_hinh' => "quanjeanG1.jpg",
                'sp_thongTin' => 'Quần jean G1 rách với gam màu sáng cá tính, thích hợp cho những bạn từ 45 đến 50 kg',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 32,
                'sp_ten' => 'QUẦN JEAN G2',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanG2.jpg",
                'sp_thongTin' => 'Quần jean G2 rách với gam màu sáng cá tính, thích hợp cho những bạn từ 45 đến 50 kg',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 33,
                'sp_ten' => 'QUẦN JEAN G3',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanG3.jpg",
                'sp_thongTin' => 'Quần jean trơn G3 với gam màu sáng cá tính, thích hợp cho những bạn từ 45 đến 50 kg',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 34,
                'sp_ten' => 'QUẦN JEAN G4',
                'sp_gia' => '340000',
                'sp_hinh' => "quanjeanG4.jpg",
                'sp_thongTin' => 'Quần jean G4 rách với gam màu sáng cá tính, thích hợp cho những bạn từ 45 đến 50 kg',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 35,
                'sp_ten' => 'QUẦN JEAN G5',
                'sp_gia' => '440000',
                'sp_hinh' => "quanjeanG5.jpg",
                'sp_thongTin' => 'Quần jean G5 rách với gam màu sáng cá tính, thích hợp cho những bạn từ 45 đến 50 kg',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 36,
                'sp_ten' => 'QUẦN SHORT G1',
                'sp_gia' => '245000',
                'sp_hinh' => "quansortG1.jpg",
                'sp_thongTin' => 'Quần short G1 màu trắng, cute, cá tính cho những cô nàng năng động, thích hợp cho những bạn từ 45 đến 50 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 37,
                'sp_ten' => 'QUẦN SHORT G2',
                'sp_gia' => '215000',
                'sp_hinh' => "quansortG2.jpg",
                'sp_thongTin' => 'Quần short G2 màu sáng, cute, cá tính cho những cô nàng năng động, thích hợp cho những bạn từ 45 đến 50 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 38,
                'sp_ten' => 'QUẦN SHORT G3',
                'sp_gia' => '275000',
                'sp_hinh' => "quansortG3.jpg",
                'sp_thongTin' => 'Quần short G3 màu tối, cute, cá tính cho những cô nàng năng động, thích hợp cho những bạn từ 45 đến 50 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 39,
                'sp_ten' => 'QUẦN SHORT G4',
                'sp_gia' => '275000',
                'sp_hinh' => "quansortG4.jpg",
                'sp_thongTin' => 'Quần short G4 màu sáng, cute, cá tính cho những cô nàng năng động, thích hợp cho những bạn từ 45 đến 50 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 40,
                'sp_ten' => 'QUẦN SHORT G5',
                'sp_gia' => '235000',
                'sp_hinh' => "quansortG5.jpg",
                'sp_thongTin' => 'Quần short G5 màu sáng, cute, cá tính cho những cô nàng năng động, thích hợp cho những bạn từ 45 đến 50 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 41,
                'sp_ten' => 'ĐỒ THUN ĐÔI C1',
                'sp_gia' => '570000',
                'sp_hinh' => "aothunC1.jpg",
                'sp_thongTin' => 'Đồ đôi C1 áo thun tay dài, màu đen mang lại cảm giác trẻ trung, cool ngầu cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 42,
                'sp_ten' => 'ĐỒ THUN ĐÔI C2',
                'sp_gia' => '510000',
                'sp_hinh' => "aothunC2.jpg",
                'sp_thongTin' => 'Đồ đôi C2 áo thun tay dài, màu trắng mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 43,
                'sp_ten' => 'ĐỒ THUN ĐÔI C3',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunC3.jpg",
                'sp_thongTin' => 'Đồ đôi C3 áo thun tay dài, màu xanh lá mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 44,
                'sp_ten' => 'ĐỒ THUN ĐÔI C4',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunC4.jpg",
                'sp_thongTin' => 'Đồ đôi C4 áo thun tay dài, màu vàng tươi mới mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 45,
                'sp_ten' => 'ĐỒ THUN ĐÔI C5',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunC5.jpg",
                'sp_thongTin' => 'Đồ đôi C5 áo thun tay dài, màu xanh biển mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 46,
                'sp_ten' => 'ÁO KHOÁC ĐÔI C1',
                'sp_gia' => '560000',
                'sp_hinh' => "aokhoacC1.jpg",
                'sp_thongTin' => 'Áo khoác đôi C1, vải dù 2 lớp, màu trắng mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 47,
                'sp_ten' => 'ÁO KHOÁC ĐÔI C2',
                'sp_gia' => '560000',
                'sp_hinh' => "aokhoacC2.jpg",
                'sp_thongTin' => 'Áo khoác đôi C2, vải dù 2 lớp, màu đen mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 48,
                'sp_ten' => 'ÁO KHOÁC ĐÔI C3',
                'sp_gia' => '560000',
                'sp_hinh' => "aokhoacC3.jpg",
                'sp_thongTin' => 'Áo khoác đôi C3, vải dù 2 lớp, màu xanh đậm mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 49,
                'sp_ten' => 'ÁO KHOÁC ĐÔI C4',
                'sp_gia' => '690000',
                'sp_hinh' => "aokhoacC4.jpg",
                'sp_thongTin' => 'Áo khoác đôi C4, vải nỉ dày dặn, màu đen nón trắng mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 50,
                'sp_ten' => 'ÁO KHOÁC ĐÔI C5',
                'sp_gia' => '690000',
                'sp_hinh' => "aokhoacC5.jpg",
                'sp_thongTin' => 'Áo khoác đôi C5, vải nỉ dày dặn, màu xanh nhạt nón trắng mang lại cảm giác trẻ trung, năng động cho người mặc. Thích hợp cho bạn nữ từ 40 đến 55 kg. Nam từ 50 đến 70 kg.',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
           
        ];

        DB::table('sanpham')->insert($list);
    }
}
