<?php

use Illuminate\Database\Seeder;

class SanPhamTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $today = new DateTime('2020-02-27 09:00:00');
        $list=[
            [
                'sp_ma' => 1,
                'sp_ten' => 'ÁO THUN B1',
                'sp_gia' => '235000',
                'sp_hinh' => "aothunB1.jpg",
                'sp_thongTin' => 'Áo thun B1 màu đen với logo đơn giản tay ngắn, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 2,
                'sp_ten' => 'ÁO THUN B2',
                'sp_gia' => '245000',
                'sp_hinh' => "aothunB2.jpg",
                'sp_thongTin' => 'ÁO thun B2 màu vàng với họa tiết Puma tay ngắn, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 3,
                'sp_ten' => 'ÁO THUN B3',
                'sp_gia' => '245000',
                'sp_hinh' => "aothunB3.jpg",
                'sp_thongTin' => 'Áo thun B3 tay ngắn, màu đen, đa họa tiết, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 4,
                'sp_ten' => 'ÁO THUN B4',
                'sp_gia' => '265000',
                'sp_hinh' => "aothunB4.jpg",
                'sp_thongTin' => 'Áo thun B4 ráp tay, màu xám đen, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 5,
                'sp_ten' => 'ÁO THUN B5',
                'sp_gia' => '195000',
                'sp_hinh' => "aothunB5.jpg",
                'sp_thongTin' => 'Áo thun B5 tay ngắn, màu đen, logo lớn, mang lại cảm giác trẻ trung, năng động cho người mặc.',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 6,
                'sp_ten' => 'ÁO SƠ MI B6',
                'sp_gia' => '275000',
                'sp_hinh' => "aosomiB6.jpg",
                'sp_thongTin' => 'Áo sơ mi B6 trắng tay dài',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 7,
                'sp_ten' => 'ÁO SƠ MI B7',
                'sp_gia' => '275000',
                'sp_hinh' => "aosomiB7.jpg",
                'sp_thongTin' => 'Áo sơ mi B7 sọc xám đen tay dài',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 8,
                'sp_ten' => 'ÁO SƠ MI B8',
                'sp_gia' => '295000',
                'sp_hinh' => "aosomiB8.jpg",
                'sp_thongTin' => 'Áo sơ mi B8 đen tay dài',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 9,
                'sp_ten' => 'ÁO SƠ MI B9',
                'sp_gia' => '295000',
                'sp_hinh' => "aosomiB9.jpg",
                'sp_thongTin' => 'Áo sơ mi B9 đỏ tay dài phối họa tiết trắng',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 10,
                'sp_ten' => 'ÁO SƠ MI B10',
                'sp_gia' => '285000',
                'sp_hinh' => "aosomiB10.jpg",
                'sp_thongTin' => 'Áo sơ mi B10 màu trắng khói pha xanh tay dài',
                // 'sp_trangThai' => '2',
                'l_ma' => '1',
            ],
            [
                'sp_ma' => 11,
                'sp_ten' => 'QUẦN JEAN B1',
                'sp_gia' => '425000',
                'sp_hinh' => "quanjeanB1.jpg",
                'sp_thongTin' => 'QUẦN JEAN B1 với gam màu sáng, thêu chữ nhỏ',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 12,
                'sp_ten' => 'QUẦN JEAN B2',
                'sp_gia' => '365000',
                'sp_hinh' => "quanjeanB2.jpg",
                'sp_thongTin' => 'QUẦN JEAN B2 đen, siêu ngầu',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 13,
                'sp_ten' => 'QUẦN JEAN B3',
                'sp_gia' => '445000',
                'sp_hinh' => "quanjeanB3.jpg",
                'sp_thongTin' => 'QUẦN JEAN B3 xanh đen rách cá tính',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 14,
                'sp_ten' => 'QUẦN JEAN B4',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanB4.jpg",
                'sp_thongTin' => 'QUẦN JEAN B4 đen năng động',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 15,
                'sp_ten' => 'QUẦN JEAN B5',
                'sp_gia' => '425000',
                'sp_hinh' => "quanjeanB5.jpg",
                'sp_thongTin' => 'QUẦN JEAN B5 rách với gam màu sáng năng động',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 16,
                'sp_ten' => 'QUẦN TÂY NAM B1',
                'sp_gia' => '315000',
                'sp_hinh' => "quantayB1.jpg",
                'sp_thongTin' => 'QUẦN TÂY NAM B1 màu đen thanh lịch',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 17,
                'sp_ten' => 'QUẦN TÂY NAM B2',
                'sp_gia' => '315000',
                'sp_hinh' => "quantayB2.jpg",
                'sp_thongTin' => 'QUẦN TÂY NAM B2 màu trắng sang trọng',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 18,
                'sp_ten' => 'KAKI NAM B3',
                'sp_gia' => '345000',
                'sp_hinh' => "quankakiB3.jpg",
                'sp_thongTin' => 'QUẦN KAKI NAM B3 đen',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 19,
                'sp_ten' => 'QUẦN TÂY B4',
                'sp_gia' => '365000',
                'sp_hinh' => "quantayB4.jpg",
                'sp_thongTin' => 'QUẦN TÂY NAM B4 sọc đen',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 20,
                'sp_ten' => 'KAKI NAM B5',
                'sp_gia' => '245000',
                'sp_hinh' => "quankakiB5.jpg",
                'sp_thongTin' => 'QUẦN KAKI NAM B5 xanh',
                // 'sp_trangThai' => '2',
                'l_ma' => '2',
            ],
            [
                'sp_ma' => 21,
                'sp_ten' => 'ÁO THUN G0',
                'sp_gia' => '185000',
                'sp_hinh' => "aothunG0.jpg",
                'sp_thongTin' => 'Áo thun G0 croptop xanh dương cá tính',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 22,
                'sp_ten' => 'ÁO THUN G1',
                'sp_gia' => '185000',
                'sp_hinh' => "aothunG1.jpg",
                'sp_thongTin' => 'Áo thun G1 ôm body tay dài , sọc ngang',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 23,
                'sp_ten' => 'ÁO THUN G2',
                'sp_gia' => '225000',
                'sp_hinh' => "aothunG2.jpg",
                'sp_thongTin' => 'Áo thun G2 in hoạt hình vui nhộn, phối tay xanh',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 24,
                'sp_ten' => 'ÁO LEN G3',
                'sp_gia' => '315000',
                'sp_hinh' => "aolenG3.jpg",
                'sp_thongTin' => 'Áo len G3 sọc trắng xinh xắn',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 25,
                'sp_ten' => 'ÁO LEN G4',
                'sp_gia' => '295000',
                'sp_hinh' => "aolenG4.jpg",
                'sp_thongTin' => 'Áo len G4 xanh lam tay dài đáng yêu',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 26,
                'sp_ten' => 'ÁO SƠ MI G5',
                'sp_gia' => '235000',
                'sp_hinh' => "aosomiG5.jpg",
                'sp_thongTin' => 'Áo sơ mi G5 xám in chữ đen',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 27,
                'sp_ten' => 'ÁO SƠ MI G6',
                'sp_gia' => '235000',
                'sp_hinh' => "aosomiG6.jpg",
                'sp_thongTin' => 'Áo sơ mi G6 trắng đen phối hoạt hình cực cool',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 28,
                'sp_ten' => 'ÁO SƠ MI G7',
                'sp_gia' => '235000',
                'sp_hinh' => "aosomiG7.jpg",
                'sp_thongTin' => 'Áo sơ mi G7 phối caro nâu vàng',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 29,
                'sp_ten' => 'ÁO SƠ MI G8',
                'sp_gia' => '235000',
                'sp_hinh' => "aosomiG8.jpg",
                'sp_thongTin' => 'Áo sơ mi G8 phối caro đen đỏ',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 30,
                'sp_ten' => 'ÁO SƠ MI G9',
                'sp_gia' => '255000',
                'sp_hinh' => "aosomiG9.jpg",
                'sp_thongTin' => 'Áo sơ mi G9 trắng không nhăn',
                // 'sp_trangThai' => '2',
                'l_ma' => '3',
            ],
            [
                'sp_ma' => 31,
                'sp_ten' => 'QUẦN JEAN G1',
                'sp_gia' => '440000',
                'sp_hinh' => "quanjeanG1.jpg",
                'sp_thongTin' => 'Quần jean G1 rách với gam màu sáng đáng yêu',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 32,
                'sp_ten' => 'QUẦN JEAN G2',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanG2.jpg",
                'sp_thongTin' => 'Quần jean G2 ống rộng với gam màu sáng cá tính',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 33,
                'sp_ten' => 'QUẦN JEAN G3',
                'sp_gia' => '345000',
                'sp_hinh' => "quanjeanG3.jpg",
                'sp_thongTin' => 'Quần jean G3 xanh ống rộng',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 34,
                'sp_ten' => 'QUẦN JEAN G4',
                'sp_gia' => '340000',
                'sp_hinh' => "quanjeanG4.jpg",
                'sp_thongTin' => 'Quần jean G4 ôm trắng xanh cá tính',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 35,
                'sp_ten' => 'QUẦN JEAN G5',
                'sp_gia' => '440000',
                'sp_hinh' => "quanjeanG5.jpg",
                'sp_thongTin' => 'Quần jean G5 đen cho bạn gái trẻ trung, năng động',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 36,
                'sp_ten' => 'QUẦN SHORT G6',
                'sp_gia' => '245000',
                'sp_hinh' => "quansortG6.jpg",
                'sp_thongTin' => 'Quần short G6 màu bạc',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 37,
                'sp_ten' => 'QUẦN SHORT G7',
                'sp_gia' => '215000',
                'sp_hinh' => "quansortG7.jpg",
                'sp_thongTin' => 'Quần short G7 kaki màu nâu sáng',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 38,
                'sp_ten' => 'QUẦN SHORT G8',
                'sp_gia' => '275000',
                'sp_hinh' => "quansortG8.jpg",
                'sp_thongTin' => 'Quần short G8 với gam màu sáng năng động',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 39,
                'sp_ten' => 'QUẦN SHORT G9',
                'sp_gia' => '275000',
                'sp_hinh' => "quansortG9.jpg",
                'sp_thongTin' => 'Quần short G9 trắng',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 40,
                'sp_ten' => 'QUẦN SHORT G10',
                'sp_gia' => '235000',
                'sp_hinh' => "quansortG10.jpg",
                'sp_thongTin' => 'Quần short G10 đen, năng động',
                // 'sp_trangThai' => '2',
                'l_ma' => '4',
            ],
            [
                'sp_ma' => 41,
                'sp_ten' => 'ĐỒ ĐÔI CP1',
                'sp_gia' => '570000',
                'sp_hinh' => "aothunCP1.jpg",
                'sp_thongTin' => 'Đồ đôi CP1 áo thun tay dài, màu vàng',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 42,
                'sp_ten' => 'ĐỒ ĐÔI CP2',
                'sp_gia' => '510000',
                'sp_hinh' => "aothunCP2.jpg",
                'sp_thongTin' => 'Đồ đôi CP2 áo thun tay dài, màu đen',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 43,
                'sp_ten' => 'ĐỒ ĐÔI CP3',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunCP3.jpg",
                'sp_thongTin' => 'Đồ đôi CP3 áo thun tay ngắn, màu trắng có cổ',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 44,
                'sp_ten' => 'ĐỒ ĐÔI CP4',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunCP4.jpg",
                'sp_thongTin' => 'Đồ đôi CP4 áo thun tay ngắn, màu đen có cổ',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 45,
                'sp_ten' => 'ĐỒ ĐÔI CP5',
                'sp_gia' => '530000',
                'sp_hinh' => "aothunCP5.jpg",
                'sp_thongTin' => 'Đồ đôi CP5 áo thun tay dài, màu vàng cute',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 46,
                'sp_ten' => 'ĐỒ ĐÔI CP6',
                'sp_gia' => '730000',
                'sp_hinh' => "aokhoacCP6.jpg",
                'sp_thongTin' => 'Đồ đôi CP6 áo khoác đỏ đen cá tính',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 47,
                'sp_ten' => 'ĐỒ ĐÔI CP7',
                'sp_gia' => '730000',
                'sp_hinh' => "aokhoacCP7.jpg",
                'sp_thongTin' => 'Đồ đôi CP7 áo khoác đen trắng cá tính',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 48,
                'sp_ten' => 'ĐỒ ĐÔI CP8',
                'sp_gia' => '560000',
                'sp_hinh' => "aokhoacCP8.jpg",
                'sp_thongTin' => 'Đồ đôi CP8 áo khoác dù đen trắng',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 49,
                'sp_ten' => 'ĐỒ ĐÔI CP9',
                'sp_gia' => '690000',
                'sp_hinh' => "aokhoacCP9.jpg",
                'sp_thongTin' => 'Đồ đôi CP9 áo khoác kaki xám trắng',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
            [
                'sp_ma' => 50,
                'sp_ten' => 'ĐỒ ĐÔI CP10',
                'sp_gia' => '690000',
                'sp_hinh' => "aokhoacCP10.jpg",
                'sp_thongTin' => 'Đồ đôi CP10 áo khoác kaki trắng xanh',
                // 'sp_trangThai' => '2',
                'l_ma' => '5',
            ],
           
        ];

        DB::table('sanpham')->insert($list);
    }
}
